version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: java-explore-with-me-stats-server
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstat
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=explorerwithme
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:13.7-alpine
    container_name: db-stat
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=explorerwithme
      - POSTGRES_PASSWORD=ewm

  main-server:
    build: main-service
    image: java-explore-with-me-main-server
    container_name: ewm-main-service
    depends_on:
      - main-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewmmain
      - EWM_SERVER_URL=http://main-db:9191
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=explorerwithme
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=ewmmain
      - POSTGRES_USER=explorerwithme
      - POSTGRES_PASSWORD=ewm



